# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install system dependencies; using slim debian base ensures availability of prebuilt wheels
RUN apt-get update && apt-get install -y build-essential cmake && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip \
    && pip install .

# Copy the remaining application code
COPY . ./

# Set default command
CMD ["python", "run.py"]
